export enum JoinPhase {
  NICKNAME = 0,
  SEX,
  BIRTHDAY,
  LIVING,
  INFER_PERIOD,
  INFER_CARE,
  INFER_CAUSE,
  INFER_COST,
  INFER_SUPPORT,
  INFER_WORK_COMPREHENSION,
  INFER_COMMUNICATION,
  DEPRESSION_TEST,
}
